### ISSUE TITLE
Sign assemblies

### ISSUE THREAD

**Issue by drewnoakes** [drewnoakes/xmp-core-dotnet#11]
Some users (https://github.com/drewnoakes/metadata-extractor-dotnet/issues/49) require strong names on assemblies.

**Comment by dpeacock** [comment]
+1 also interested in this.

**Comment by Tasteful** [comment]
Hi @drewnoakes we found out the `metadata-extractor-dot net` and found this issues regarding strong name signing. I know that it exists a lot for and against strong name signing of assemblies, developers (me with more) need strong name signing on assemblies to be able to run them in example SharePoint or been able to qualify the work for Microsoft application certification.

If you change and start using strong name signing on the current assemblies will make them break for users that is currently using them. That is a decisions for acceptable breaking change or not. Other way some package owner are doing is to provide two different versions, with and without strong name signing in different package, example dapper with https://www.nuget.org/packages/Dapper/ and https://www.nuget.org/packages/Dapper.StrongName/.

Is it possible that you (as package owner) can provide strong name signed assemblies in nuget packages as well? If so I can help out to make the `xmp-core-dotnet` and `metadata-extractor-dot net` strong name signed in either the current package or in package with new name.

**Comment by drewnoakes** [comment]
I'd like to help out those poor souls who need strong naming. Thanks @whopper and @Tasteful for your research and PRs here.

Adding a new project/package seems like a sensible approach. The question then is how to best achieve this, with the minimum of fuss and maintenance burden.

@Tasteful's PR's #25 and drewnoakes/metadata-extractor-dotnet#92 script a fair bit of the work here, which is great. I was holding off on merging them though until VS2017 and the new .csproj format were released, as the .xproj files will go away shortly.

How would we best create a new project/package with the new project formats?

**Comment by Tasteful** [comment]
With the new format I think it is possible to fix my PR-version but with only one project and conditions in the file. I haven't tested that with the new format yet.

@drewnoakes What's the time plan to upgrade the project to the new csproj format?

**Comment by drewnoakes** [comment]
I was hoping the new project format would allow that. It'd definitely be nicer to have a single project in VS while coding.

There is no concrete timeframe. If you wanted to take a look at it, go ahead.

**Comment by drewnoakes** [comment]
This is now available via the [`XmpCore.StrongName`](https://www.nuget.org/packages/XmpCore.StrongName) package. Many thanks to @Tasteful for his help putting this together.
