### ISSUE TITLE
Implement Language property for XmpProperty682

### ISSUE THREAD

**Issue by CanyonJim** [drewnoakes/xmp-core-dotnet#13]
**XmpProperty682** currently always returns _null_ for the Language property even when an _xml:lang_ qualifier is present and the **Options** flag **HasLanguage** is _true_.  I ran into this trying to enumerate the localization languages available for descriptions, copyrights, etc.  Using **XmpMeta.GetArrayItem** to enumerate the localized text entries returns **XmpProperty682** properties.  **XmpMeta.GetLocalizedText** is the only way to get an **XmpProperty407** property, which requires knowing what the **Language** will be.

It would seem all **XmpProperty682.Language** would have to do is test the **Options.HasLanguage** flag to either return the same value as **XmpProperty407** or _null_ as it does now.

...Jim Hansen

**Comment by drewnoakes** [comment]
It seems you know much more about this than I do. Can you make a pull
request?

**Comment by CanyonJim** [comment]
I'm an old "seat of the pants" programmer (~50 yrs. professional experience) and don't have any experience with "pull requests", but I'll look into it.  I don't mind making and debugging the change as it looks straightforward, but am not familiar with the procedures and etiquette of working on GitHub projects.

While I'm at it, I would like to add and register an XMP namespace for Lightroom metadata, if that is appropriate.

**Comment by drewnoakes** [comment]
If you're still interested in looking through this I'm happy to help with the pull request part. Thankfully most of the work will be in your wheelhouse--namely, writing the code.

The high-level overview:

1. Fork this repository on GitHub (button at top right of this page)
2. Clone your fork to your local PC
3. Create a branch locally for your fix
4. Code your changes on this local branch
5. Commit them, then push them
6. Visit your forked repo on GitHub and you'll see some buttons about making a pull request

This repo is intended to be a faithful reproduction on the Java library produced by Adobe. If this is a bu, then it might be worth seeing it exists in the Java version too.

**Comment by kwhopper** [comment]
@CanyonJim - Do you have an example XMP string or image where this occurs? Thanks

**Comment by drewnoakes** [comment]
@kwhopper do you think this can be closed now?

**Comment by kwhopper** [comment]
Possibly, but the merge was mostly to clarify that there aren't really two versions of XmpProperty. I'd like to see if @CanyonJim can try his code again. Language will still be null for an instance that modeled the "682" version. "getLanguage()" in the original Java only has "return null;" in it so I think this was intended.

**Comment by CanyonJim** [comment]
I originally ran into this issue while developing software for cataloging and processing scans of a few thousand old family photos.  Because we are in touch with relatives in Denmark and Sweden I thought we might want to take advantage of the multiple language features in the metadata.

I was willing to work on the C# changes, but I am not interested in learning Java.  Furthermore I could not find a way to enter or view multiple language text fields in Photoshop or Bridge, so I dropped the idea.

I think it would be good if the language information was enumerable and I would use it in my program if the information was enumerable in the C# version, but I've moved on to other aspects of my project for now.  I'm really more interested in cataloging and processing the photographs and sharing them with my extended family than I am in the software development itself.

When I have time I'll update my project and look at the changes cited above.

Thank you for your help.

...Jim

**Comment by drewnoakes** [comment]
@CanyonJim the Java version is owned by Adobe anyway, so it'd be harder to upstream changes (it's not hosted publicly and I don't know of an issue tracker). But if there's a clear defect here, we can fix it in the C# version.

Biggest barrier to the fix is the absence of test data. If you can provide a sample XMP packet, we can look into it. You can remove any identifying or personal info if you like.
