### ISSUE TITLE
How to write only Xmp metadata using Xmp core

### ISSUE THREAD

**Issue by sour7230** [drewnoakes/xmp-core-dotnet#34]
Dear All,

i wont to write only  xmp meta data to any file. we go for lot of  R&D but they did not work for me at. all.so it is very urgent,anybody help me..

**Comment by drewnoakes** [comment]
You can use this library to produce XMP formatted XML, but there is no support for writing it into a container file such as JPEG/etc.

**Comment by sour7230** [comment]
Dear drewnoakes,

i wont to do for all file. and can  you provide another way to do this.  furthermore can you provide me some code to do this.

**Comment by drewnoakes** [comment]
As I said, there is no support for writing it into a container file such as JPEG/etc. You would need to implement this yourself or find another library.

This library is a mirror of Adobe's XMPCore project (for Java) which also does not have this capability, hence we won't be adding it to this project.
