### ISSUE TITLE
UTF-16 is not supported

### ISSUE THREAD

**Issue by GilesTT** [drewnoakes/xmp-core-dotnet#35]
Thanks for the Sample usage example.  I have tried this on some files with XMP tags (generated by Picasa), and I get the following exception : "UTF-16 is not a supported encoding.".  Do you have any advice on how to overcome this please?  (the tags show up ok when checked at: http://exif.regex.info/exif.cgi )

**Comment by kwhopper** [comment]
Do you have an image we can test with? There are some Encoding limitations with .NET Standard 1.0 but I'd like to look at your file if possible. Thanks

**Comment by GilesTT** [comment]
Thanks for the reply, here is an image: 
![family1](https://cloud.githubusercontent.com/assets/28028098/25422232/2506f7e4-2a58-11e7-9500-b22f5d19030d.JPG)
(Ive actually been using the MetadataExtractor library, - but I think that uses this XMP-core-dotnet (which I updated to the latest version) and it is the XMP - Region Name tag I was after.  Thanks.

**Comment by kwhopper** [comment]
I'm able to read the XMP with the full .NET framework version but will try to setup a .NET Core test also. What code are you using to try and parse this, and on what platform? Thanks

**Comment by GilesTT** [comment]
I'm using:  Microsoft Visual Studio Community 2015
Version 14.0.24720.00 Update 1
Microsoft .NET Framework Version 4.6.01055 
Visual C# 2015
OS :	Microsoft Windows 7 Professional  Version	6.1.7601 Service Pack 1 Build 7601
  
XmpCore v5.1.3  (Downloaded via NuGet)

Code is:
using XmpCore;
using System.IO;
...
 IXmpMeta xmp;
 using (var stream = File.OpenRead(FilenameTextBox.Text))
     xmp = XmpMetaFactory.Parse(stream);  //****** Throws Exception here.

 foreach (var property in xmp.Properties)
     Console.WriteLine($"Path={property.Path} Namespace={property.Namespace} Value={property.Value}");

Thanks.

**Comment by kwhopper** [comment]
Your usage isn't quite right. The sample usage with XmpMetaFactory.Parse expects the input to contain only XMP text. In this case, you're giving it the entire JPEG as the input. XmpMetaFactory doesn't know how to parse through a JPEG file looking for embedded XMP by itself; that's what MetadataExtractor provides.  :)

Give this a try and see if you get better results (you'll need 'using MetadataExtractor;' at the top):

```
using (var stream = File.OpenRead(fullpath))
{
    var dirs = ImageMetadataReader.ReadMetadata(fullpath);

    var xmpDir = dirs.OfType<XmpDirectory>().FirstOrDefault();
    if (xmpDir?.XmpMeta != null)
    {
        foreach (var property in xmpDir.XmpMeta.Properties)
            Console.WriteLine($"Path={property.Path} Namespace={property.Namespace} Value={property.Value}");
    }
}
```

**Comment by kwhopper** [comment]
* fixed a code typo in the previous comment

**Comment by GilesTT** [comment]
Thank you so much, that works great.

**Comment by SimonKravis** [comment]
Had this problem (UTF-16 not supported encoding ) tried code suggested by kwhopper but get error "Type or Namespace XmpDirectory not found"  at  line
` var xmpDir = dirs.OfType<XmpDirectory>().FirstOrDefault();`  

and line
`if (xmpDir?.XmpMeta != null)`

gives syntax error  ":" expected after xmpDir?

**Comment by SimonKravis** [comment]
After posting I find the answer to both problems:
```var directories = ImageMetadataReader.ReadMetadata(file);
                foreach (var directory in directories)
                {
                    if (directory.Name == "XMP")
                    {
                        IXmpMeta xmp;                     
                        using (var stream = File.OpenRead(file))
                        {
                            var dirs = ImageMetadataReader.ReadMetadata(stream);
                            var xmpDir = dirs.OfType<MetadataExtractor.Formats.Xmp.XmpDirectory>().FirstOrDefault();
                            if (xmpDir.XmpMeta != null)
                            {
                                foreach (var property in xmpDir.XmpMeta.Properties)
                                    txtMetaData.Text +=  "XMP Field \t" + property.Path + "\t" + property.Value + "\r\n";
                            }
                        }                       
                    }
```

**Comment by SimonKravis** [comment]
I get error "Error processing XMP data: Unsupported Encoding" for one particular JPEG file with the above code with xmpDir .XmpMeta = null, but Exiftool shows many XMP fields present. Any idea what the problem might be?

**Comment by drewnoakes** [comment]
@SimonKravis your issue was fixed in drewnoakes/metadata-extractor-dotnet#154.

**Comment by Beckero84** [comment]
I'm having the same problem as GilesTT, so I stumbled on this page.

Looks like I would need a combination of XMPCore and MetadataExtractor... I simply want to extract the entire XMP xml (as a string/XDocument/...) from a given image file. 

Any idea if (and how) this is possible with these packages?

**Comment by Beckero84** [comment]
> I'm having the same problem as GilesTT, so I stumbled on this page.
> 
> Looks like I would need a combination of XMPCore and MetadataExtractor... I simply want to extract the entire XMP xml (as a string/XDocument/...) from a given image file.
> 
> Any idea if (and how) this is possible with these packages?

Think I found it.

`            
            XmpDirectory xmpDirectory = ImageMetadataReader.ReadMetadata(fileName).OfType<XmpDirectory>().FirstOrDefault();

            if (xmpDirectory == null)
            {
                return null;
            }

            string xml = XmpMetaFactory.SerializeToString(xmpDirectory.XmpMeta, new SerializeOptions { OmitPacketWrapper = true });

            //Remove the BOM if necessary
            int index = xml.IndexOf('<');
            if (index > 0)
            {
                xml = xml.Substring(index, xml.Length - index);
            }

            var document = new XmlDocument();
            document.LoadXml(xml);`

Apparently with the test file I used, the serialized string starts with a BOM, so therefore the substring.

**Comment by drewnoakes** [comment]
That should work, though it round-trips the XMP data through an object model, so the XML string you end up with might not exactly match that which was in the file. I believe it should preserve all the data, so should be fine for most use cases.
