### ISSUE TITLE
Support for UTF-16 and UTF-32?

### ISSUE THREAD

**Issue by pranavmehta** [drewnoakes/xmp-core-dotnet#36]
Is there any plans to support UTF-16 and UTF-32 encoded XMP metadata?

This library is perfect for my use except for the support of these encodings.

**Comment by drewnoakes** [comment]
Can you provide a sample image along with the actual and expected outputs?

**Comment by drewnoakes** [comment]
Ideally a sample for both encodings.

**Comment by pranavmehta** [comment]
I have only one sample at the moment. I've uploaded it here https://image.ibb.co/b5umfk/test2.jpg (Source page: https://ibb.co/e2NuY5)

The current version does not populate the XMP directory in the list of directories, and trying to read the XMP metadata forcefully throws a not supported exception. But the same XMP metadata is readable using other .Net components and can also be verified by uploading the file to http://metapicz.com/

**Comment by kwhopper** [comment]
For test2.jpg, what specific error does it return for you? When I run it (full .NET framework on Windows) the error is because of a duplicate node under the same parent, which is technically illegal in XMP. Thanks

**Comment by bvanderw** [comment]
Most of the photos we have here are from Canon cameras, and every one I have tried has failed with this error:

UTF-16 is not a supported encoding.
   at XmpCore.Impl.ByteBuffer.GetEncoding()
   at XmpCore.Impl.Latin1Converter.Convert(ByteBuffer buffer)
   at XmpCore.Impl.XmpMetaParser.ParseXmlFromByteBuffer(ByteBuffer buffer, ParseOptions options)
   at XmpCore.Impl.XmpMetaParser.ParseXmlFromInputStream(Stream stream, ParseOptions options)
   at XmpCore.Impl.XmpMetaParser.Parse(Stream stream, ParseOptions options)
   at XmpCore.XmpMetaFactory.Parse(Stream stream, ParseOptions options)

These photos are straight off the camera. I have verified with Metadata++ that they have one XMP tag (Rating).

In metadata-extractor, it returns the number of XMP tags, but does not list the individual tags.

I have attached a sample (intentionally black).

![img_0001](https://user-images.githubusercontent.com/1181271/40074357-6665650e-5847-11e8-9af8-324704f679ef.JPG)

**Comment by Yauheni1987** [comment]
Hi! How can i fix this error with UTF-16 encoding? Thank you very much!
https://www.screencast.com/t/kZ6wRfnv8n

**Comment by kwhopper** [comment]
Is it possible to get a copy of the image that has this problem? In many cases, an "encoding" error (thrown by XmpCore) can be a misnomer. The real problem typically is with illegal embedded XMP. If we could get the image it would help diagnose. Thanks

**Comment by Yauheni1987** [comment]
https://gofile.io/?c=q1WtyX
But it happens with any file i try to use...

**Comment by drewnoakes** [comment]
@Yauheni1987 you cannot pass whole image files directly to `XmpMetaFactory.Parse`. That method expects XMP data only.

If you want to get metadata from images, you'll have to use http://github.com/drewnoakes/metadata-extractor-dotnet and the `ImageMetadataReader` class.

**Comment by Yauheni1987** [comment]
Thank you for your answer. I need to read and **edit** metadata in **.eps**(vector image) files. Thats why ImageMetadataReader can't help me.

**Comment by drewnoakes** [comment]
Unfortunately then you'll need to write your own code to manipulate the EPS files. XmpCore will be able to parse and format the XMP XML for you, but you'll have to do the rest.

**Comment by kwhopper** [comment]
I believe this issue could be closed.

**Comment by drewnoakes** [comment]
Thanks @kwhopper.
