### ISSUE TITLE
Support for PCL

### ISSUE THREAD

**Issue by ravensorb** [drewnoakes/xmp-core-dotnet#4]
Any thoughts on converting this to be usable in a PCL library?

**Comment by drewnoakes** [comment]
Copying your comments from drewnoakes/metadata-extractor-dotnet#24:

> all that is needed is to switch from using System.Xml to System.Linq (XmlNode to XNode)

I won't have time to look at this for the next few months. Want to put a PR together?

**Comment by ravensorb** [comment]
Time is always the hard part :smile:  I'll see if I can get something started. If lucky, I might be able to work the bulk of the work this week, testing is another story though.

**Comment by drewnoakes** [comment]
Just a follow up on this -- metadata-extractor-dotnet (the initial client of xmp-core-dotnet) now has a PCL build that excludes XMP support as this library does not have a PCL option.

**Comment by drewnoakes** [comment]
Huge thanks to @kwhopper who has gone ahead an implemented the first cut of PCL support for XmpCode. Can someone please verify that this code is working as expected? I'm not using a PCL environment.

If it looks ok, I'll put together a new NuGet release.

**Comment by kwhopper** [comment]
I tested against some very old sample images in Adobe's XMP Toolkit SDK using a portable-enabled version of MetadataExtractor. All the supported formats read without error although I can't confirm whether that means they were read appropriately. In any case, the PCL version seems to work with those images and with the xunit test images.

**Comment by drewnoakes** [comment]
@kwhopper thanks very much for testing. I've pushed v1.2.0 to NuGet which includes the portable build of this package. Now we can look at linking it into the metadata-extractor-dotnet project too.
