### ISSUE TITLE
Create Array of Structs

### ISSUE THREAD

**Issue by sonicmouse** [drewnoakes/xmp-core-dotnet#50]
I can't find anything online on how to create an array of structs.

There is `AppendArrayItem`, but it takes a `string` as it's value, but I need it to be the actual struct. How do you make that work?

Thanks!

**Comment by kwhopper** [comment]
XMP is, fundamentally, XML - which has a string structure. What are you trying to do again? Thanks

**Comment by sonicmouse** [comment]
I need to create this XMP metadata, which is an array of structs:

	<?xpacket begin="ï»¿" id="W5M0MpCehiHzreSzNTczkc9d"?>
	<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Adobe XMP Core 7.1-c000 79.cb7c5a1, 2022/04/14-05:22:35        ">
	   <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
		  <rdf:Description rdf:about=""
				xmlns:xmpTPg="http://ns.adobe.com/xap/1.0/t/pg/"
				xmlns:stFnt="http://ns.adobe.com/xap/1.0/sType/Font#">
			 <xmpTPg:Fonts>
				<rdf:Bag>
				   <rdf:li rdf:parseType="Resource">
					  <stFnt:fontName>HelveticaLTStd-Bold</stFnt:fontName>
					  <stFnt:fontFamily>Helvetica LT Std</stFnt:fontFamily>
					  <stFnt:fontFace>Bold</stFnt:fontFace>
					  <stFnt:fontType>Open Type</stFnt:fontType>
					  <stFnt:versionString>Version 1.040;PS 003.001;Core 1.0.35;makeotf.lib1.5.4492</stFnt:versionString>
					  <stFnt:composite>False</stFnt:composite>
					  <stFnt:fontFileName>HelveticaLTStd-Bold.otf</stFnt:fontFileName>
				   </rdf:li>
				   <rdf:li rdf:parseType="Resource">
					  <stFnt:fontName>VerdanaLTStd-Bold</stFnt:fontName>
					  <stFnt:fontFamily>Verdana LT Std</stFnt:fontFamily>
					  <stFnt:fontFace>Bold</stFnt:fontFace>
					  <stFnt:fontType>Open Type</stFnt:fontType>
					  <stFnt:versionString>Version 1.040;PS 003.001;Core 1.0.35;makeotf.lib1.5.4492</stFnt:versionString>
					  <stFnt:composite>False</stFnt:composite>
					  <stFnt:fontFileName>VerdanaLTStd-Bold.otf</stFnt:fontFileName>
				   </rdf:li>
				</rdf:Bag>
			 </xmpTPg:Fonts>
		  </rdf:Description>
	   </rdf:RDF>
	</x:xmpmeta>

I know it's just XML, but I was hoping this XMPCore library would make it a lot less painful to do.

**Comment by sonicmouse** [comment]
This library is nice for reading XMP Metadata, but it's not so good for writing it. I just ended up writing XML code to take care of this. Thanks for the help anyway.
